version: '3'
services:
  db_users:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: kmp_posts
      POSTGRES_PASSWORD: kmp_posts
      POSTGRES_DB: kmp_posts

  app_users:
    image: epamsesegvanchikova/posts:v1
    ports:
      - "8090:8090"
    environment:
      DATABASE_URL: jdbc:postgresql://172.19.0.1:5433/kmp_posts
    depends_on:
      db_users:
        condition: service_started
