server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/kmp_posts}
    username: ${POSTGRES_USER:kmp_posts}
    password: ${POSTGRES_PASSWORD:kmp_posts}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  db:
    changeLog: "classpath:db/changelog-master.yml"

services:
  users:
    origin: ${USERS_ORIGIN:http://localhost:8080}