server:
  port: 8090

spring:
  datasource:
    url: ${DATABASE_URL}
    username: kmp_posts
    password: kmp_posts
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  db:
    changeLog: "classpath:db/changelog-master.yml"